apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-runner.fullname" . }}
  labels:
    {{- include "github-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  REPO_URL: {{ required "github.url is required" .Values.github.url | quote }}
  RUNNER_TOKEN: {{ required "github.runnerToken is required" .Values.github.runnerToken | quote }}
